# in _config.yml
title: "Documentation Technique Chamblandes"
logo: images/logoCh.png
execute:
    execute_notebooks: "off"

#######################################################################################
# HTML-specific settings
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  #use_issues_button: true
  #use_repository_button: false
  home_page_in_navbar: false
  extra_navbar: ""
  extra_footer: |
    <p>
    <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" />
    </a>
    <br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
    Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License
    </a>.
    </p>

